# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://drwuerz.de
title: Dr. Wuerz
email: dr.wuerzburg@gmail.com
author: Marcel Gellesch
description: > # "Write an awesome description for your new site here.
  Englisch & German Writing Coach.
  Experienced professional for Academic Writing &endash; Papers, Posters,
  Dissertations (Bachelor, Master's, Doctoral), Journal Submissions.
  Extensive knowledge of Academic Style Guidelines (MLA, APA, Chicago)
  Experienced proofreader, editor
  Writing workshops

copyright: 'Copyright &copy; 2018. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/drwuerz
